language: python
python:
  - "3.8"
before_install:
  - mv inventory.stub inventory

install:
  - pip install ansible

jobs:
  include:
    - stage: simple-check
      before_script:
        - mv variables/default.yaml.stub variables/default.yaml
      script:
        - ansible-playbook playbook.yaml -i inventory --syntax-check