---
language: python
python:
  - "3.8"
before_install:
  - mv inventory.stub inventory

install:
  - pip install ansible
  - pip install ansible-lint
  - pip install yamllint

jobs:
  include:
    - stage: simple-check
      before_script:
        - >
          mv variables/default.yaml.stub
          variables/default.yaml
      script:
        - ansible-playbook playbook.yaml -i inventory --syntax-check
    - stage: check-ddns
      before_script:
        - >
          mv variables/default.yaml.ddns_no_explicit_domain.stub
          variables/default.yaml
      script:
        - ansible-playbook playbook.yaml -i inventory --syntax-check
    - stage: check-ddns-custom
      before_script:
        - >
          mv variables/default.yaml.ddns_explicit_domain.stub
          variables/default.yaml
      script:
        - ansible-playbook playbook.yaml -i inventory --syntax-check
    - stage: ansible-lint
      before_script:
        - >
          mv variables/default.yaml.stub
          variables/default.yaml
      script:
        - ansible-lint playbook.yaml
    - stage: yaml-lint
      script:
        - yamllint . && yamllint variables/*.stub
