version: '3'
services:
        caddy:
                image: abiosoft/caddy
                container_name: "caddy"
                volumes:
                        - ./caddy/Caddyfile:/etc/Caddyfile
                        - $HOME/.caddy:/etc/caddycerts
                ports:
                        - "80:80"
                        - "443:443"
                        - "2015:2015"
                environment:
                        - CADDYPATH=/etc/caddycerts
                        - ACME_AGREE=true
                        - DOMAIN=${DOMAIN}
                restart: unless-stopped
        bitwarden:
                image: bitwardenrs/server
                container_name: bitwarden
                volumes:
                        - ./bitwarden/:/data/
                restart: unless-stopped
