---
- hosts: hosts
  become: true
  vars_files:
    - variables/default.yaml
  roles:
    - role: initial_bringup
      tags: initial
    - role: update_configuration
      tags: configure
    - role: spin_containers
      tags: run
    - role: duckdns
      tags: ddns
      when: default.ddns
