---
- name: Ensure prerequisites installed for docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    update_cache: true

- name: Ensure Docker GPG Key is present
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Ensure Docker APT Repository is present
  apt_repository:
    repo: >-
      deb [arch=amd64]
      https://download.docker.com/linux/{{ ansible_distribution|lower }}
      {{ ansible_distribution_release }}
      stable

- name: Ensure Docker is intalled
  apt:
    name: docker-ce
    update_cache: true

- name: Ensure Docker service is started
  service:
    name: docker
    state: started
    enabled: true

- name: Ensure python docker is installed
  pip:
    name:
      - docker
