---
- name: Create docker container for caddy
  docker_container:
    name: caddy
    image: abiosoft/caddy
    state: started
    pull: "{{ default.pull }}"
    restart_policy: always
    env:
      CADDYPATH: /etc/caddycerts
      ACME_AGREE: "true"
    volumes:
      - ./caddy:/etc/caddycerts
      - ./data/bitwarden_vps_docker/caddy/Caddyfile:/etc/Caddyfile
    ports:
      - 80:80
      - 443:443
- name: Create docker container for bitwarden
  docker_container:
    name: bitwarden
    image: bitwardenrs/server
    state: started
    pull: "{{ default.pull }}"
    restart_policy: always
    volumes:
      - ./data/bitwarden_vps_docker/bitwarden:/data

- name: Ensure containers are connected to correct network
  docker_network:
    name: bitwarden_vps_docker
    connected:
      - bitwarden
      - caddy