---
name: Ansible CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Getting configuration from GitHub
        uses: actions/checkout@v1
      - name: Running yamllint
        uses: "docker://pipelinecomponents/yamllint:latest"
        with:
          args: yamllint .
      - name: Running yamllint on variables
        uses: "docker://pipelinecomponents/yamllint:latest"
        with:
          args: yamllint variables/*.stub

  ansiblelint:
    runs-on: ubuntu-latest
    steps:
      - name: Getting configuration from GitHub
        uses: actions/checkout@v1
      - name: Running ansible-lint
        uses: "docker://pipelinecomponents/ansible-lint:latest"
        with:
          args: ansible-lint playbook.yaml

  ansiblesyntax:
    runs-on: ubuntu-latest
    steps:
      - name: Getting configuration from GitHub
        uses: actions/checkout@v1
      - name: Copy stub variable
        run: |
          cp variables/default.yaml.stub variables/default.yaml
          cp inventory.stub inventory
      - name: Installing ansible
        run: |
          sudo apt-get install ansible
      - name: Running ansible-playbook syntax check
        run: |
          ansible-playbook playbook.yaml -i inventory --syntax-check
