---
name: Ansible CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Getting configuration from GitHub
        uses: actions/checkout@v1
      - name: Running yamllint
        uses: "docker://pipelinecomponents/yamllint:latest"
        with:
          args: yamllint . && yamllint variables/*.stub
